### ISSUE TITLE
Espy supporting DNS Logs

### ISSUE THREAD

**Issue by william-stearns** [activecm/espy#37]
To my understanding, Espy ingests Sysmon Event ID3 logs delivered via winlogbeat to produce zeek-compatible conn-Logs, that can then be processed by AC-Hunter.

Is it feasible to also convert Sysmon Event ID 22 (DnsQuery) to produce zeek-compatible dns-logs?

 

As an internal test, I configured Sysmon to produce ID 22 events, winlogbeat to also forward them to redis/Espy and finally the espy config to forward it to elasticsearch/BeaKer. They now successfully show up in Kibana, which is a good start. Nevertheless, it would be way better if those logs are also converted to zeek dns-logs. The the DNS information can also be analyzed in AC-Hunter to detect  DNS tunneling. On the long run, this may also enable FQDN-based beacon detection (that is planned for v5.1/v5.2 as far as I know) in environments where sensors cannot be deployed and only agents can be used.

 

Is anything planned in this regard?

 

Cheers

Clemens

**Comment by Zalgo2462** [comment]
This was implemented in https://github.com/activecm/espy/pull/47
